name = "git-command-actor"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/git-command-actor/./target/wasm32-unknown-unknown/release/git_command_actor.wasm"
save_chain = true
init_state = "/Users/colinrozzi/work/actor-registry/git-command-actor/init.json"

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "process"

[handlers.config]
max_processes = 1
max_output_buffer = 1048576

[[handlers]]
type = "timing"

[handlers.config]
max_sleep_duration = 60000
min_sleep_duration = 1
